name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch:

# This specifically gives the bot permission to push files to your repo
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    steps:
      # Updated to v4 to fix the Node.js warning
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.README }}
        with:
          USERNAME: ${{ github.repository_owner }}
